version: '3.7'

services:
  app:
    build:
      context: .
      args:
      - DEBUG_ARG=True
      - ALLOWED_HOSTS_ARG=127.0.0.1,localhost
      - SECRET_KEY_ARG=CHAVENAOSEGURA
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=senhadanasa
      - REQUIREMENTS_ARG=requirements-dev.txt
    ports:
      - 8000:8000
    tty: true
    command: ["/tini", "--", "./start.sh"]
    volumes:
      - ./src:/src

    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senhadanasa
